version: 0.2

phases:
  init_terraform:
    commands:
    - yum install -y yum-utils shadow-utils
    - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    - yum -y install terraform
  build:
    commands:
      - terraform version 
